### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by MerlockMoe** [grimmlab/UAVWeedSegmentation#3]
Servus,

Ich habe auf Basis des Dockerimages von dustynv/l4t-pytorch:36.2.0 und einem compose um dieses git Repo erweitert und die requirements.txt als run befehl intergriert. Alles läuft auf einem Nvidia Jetson Orin Nx 8GB mit JetPack5.0 und Ubuntu 20.04.

Das Ausführen des save_patches.py scripts funktioniert, aber wenn ich versuche "python3 predict_testset.py models/model_unet_resnet34_dil0_bilin1_retrained.pt test" auszuführen, bekomme ich folgenden Fehler:
Traceback (most recent call last):
  File "/tmp/joe/UAVWeedSegmentation/predict_testset.py", line 6, in <module>
    from utils.train import seed_all, set_model, get_calculated_means_stds_trainval, get_patch_lists
  File "/tmp/joe/UAVWeedSegmentation/utils/train.py", line 6, in <module>
    from utils.dataset import UAVDatasetPatches
  File "/tmp/joe/UAVWeedSegmentation/utils/dataset.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
**ImportError: libpng15-7864b8f1.so.15.13.0: cannot open shared object file: No such file or directory**

So wie ich das verstehe ist das ein Problem der opencv library. Ich habe versucht manuell andere Versionen zu installieren, aber lande bei dem gleichen Fehler.

Haben Sie einen Lösungsvorschlag?

LG

**Comment by MerlockMoe** [comment]
Nach dem ich opencv-python deinstalliert habe und dann:
_apt-get update; apt-get install -y libsm6 libxext6 libxrender-dev; pip install opencv-python_
Ohne spezifische version, scheint der cv2 Import zu funktionieren. Jetzt stehe ich aber vor dem Problem, dass pytorch mein CUDA nicht erkennt. der Befehl: _torch.cuda.is_available()_ gibt mir _False_ zurück. Wenn ich allerdings mit _nvcc --version_ checke, habe ich folgenden output: _nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:08:11_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0_

Ich weiß, dass dies eher ein Problem von Nvidia und ihren nicht ganz so toll dokumentierten Jetsons ist, aber vielleicht haben Sie hierfür einen Lösungsvorschlag. Vielen Dank für Ihre Zeit!

**Comment by ngenze** [comment]
Hallo, 

ich habe opencv nur zum laden der Bilder und Masken benutzt. Da können Sie auch scikit-image (pip install scikit-image) verwenden und den code in utils/dataset.py (Zeile 19-21) wie folgt ersetzen: 

```
from skimage import io as skio

# ...

image = skio.imread(str(self.img_list[idx]))
mask = skio.imread(str(self.img_list[idx]), as_gray=True)
```

Sagen Sie bitte Bescheid, wenn das den Fehler gelöst hat.

**Comment by MerlockMoe** [comment]
Danke für den Hinweis. Das hat den Fehler an der Stelle zwar behoben, jetzt wird aber beim import von _albumentations_ in _train.py_ der gleiche Fehler geworfen. Scheinbar ist diese lib abhängig von cv2. Den ursprünglichen Fehler konnte ich aber zuvor schon mit neuen requirements (neuere Version von cv2) lösen. Allerdings besteht weiterhin der Fehler, dass torch meine cuda packages nicht sieht, wie in meinem Zweiten Kommentar genauer beschrieben. Ich hab das gefühl, dass was mit meinen environment variablen im docker image nicht stimmt.

**Comment by MerlockMoe** [comment]
Traceback (most recent call last):
  File "/tmp/joe/UAVWeedSegmentation/predict_testset.py", line 6, in <module>
    from utils.train import seed_all, set_model, get_calculated_means_stds_trainval, get_patch_lists
  File "/tmp/joe/UAVWeedSegmentation/utils/train.py", line 11, in <module>
    import albumentations as A
  File "/usr/local/lib/python3.10/dist-packages/albumentations/__init__.py", line 5, in <module>
    from .core.composition import *
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/composition.py", line 8, in <module>
    from albumentations.augmentations.keypoints_utils import KeypointsProcessor
  File "/usr/local/lib/python3.10/dist-packages/albumentations/augmentations/__init__.py", line 4, in <module>
    from .functional import *
  File "/usr/local/lib/python3.10/dist-packages/albumentations/augmentations/functional.py", line 7, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libpng15-7864b8f1.so.15.13.0: cannot open shared object file: No such file or directory

**Comment by MerlockMoe** [comment]
> Nach dem ich opencv-python deinstalliert habe und dann: _apt-get update; apt-get install -y libsm6 libxext6 libxrender-dev; pip install opencv-python_ Ohne spezifische version, scheint der cv2 Import zu funktionieren. Jetzt stehe ich aber vor dem Problem, dass pytorch mein CUDA nicht erkennt. der Befehl: _torch.cuda.is_available()_ gibt mir _False_ zurück. Wenn ich allerdings mit _nvcc --version_ checke, habe ich folgenden output: _nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2023 NVIDIA Corporation Built on Tue_Aug_15_22:08:11_PDT_2023 Cuda compilation tools, release 12.2, V12.2.140 Build cuda_12.2.r12.2/compiler.33191640_0_
> 
> Ich weiß, dass dies eher ein Problem von Nvidia und ihren nicht ganz so toll dokumentierten Jetsons ist, aber vielleicht haben Sie hierfür einen Lösungsvorschlag. Vielen Dank für Ihre Zeit!

Das ist mein aktuelles Problem:
_Using Seed 42
Found 7 images and masks in data/test
Traceback (most recent call last):
  File "/tmp/joe/UAVWeedSegmentation/predict_testset.py", line 49, in <module>
    loaded_model = torch.load(model_save_path)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1422, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1392, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1366, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 381, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 274, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 258, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU._

**Comment by ngenze** [comment]
Hallo, 

das scheint alles an CUDA zu liegen bzw. den Versionen von PyTorch und CUDA, die miteinander kompatibel sein sollten. Der Code in diesem GitHub Repository wurde auf einem Ubuntu System getestet und funktioniert einwandfrei. Ich kann leider keinen Support zu CUDA-spezifischen Fehlermeldungen auf einem Jetson Orin Nx geben, da ich Ihren Fehler nicht reproduzieren kann.

**Comment by MerlockMoe** [comment]
Hi,

das CUDA problem habe ich gelöst bekommen. jetzt stecke ich hier fest: 
Traceback (most recent call last):
```
  File "predict_testset.py", line 6, in <module>
    from utils.train import seed_all, set_model, get_calculated_means_stds_trainval, get_patch_lists
  File "/etc/joe/UAVWeedSegmentation/utils/train.py", line 11, in <module>
    import albumentations as A
  File "/usr/local/lib/python3.8/dist-packages/albumentations/__init__.py", line 5, in <module>
    from .core.composition import *
  File "/usr/local/lib/python3.8/dist-packages/albumentations/core/composition.py", line 8, in <module>
    from albumentations.augmentations.keypoints_utils import KeypointsProcessor
  File "/usr/local/lib/python3.8/dist-packages/albumentations/augmentations/__init__.py", line 4, in <module>
    from .functional import *
  File "/usr/local/lib/python3.8/dist-packages/albumentations/augmentations/functional.py", line 7, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libpng15-7864b8f1.so.15.13.0: cannot open shared object file: No such file or directory
```
Es liegt definitiv an opencv. Ich habe verschiedenste Versionen jetzt ausgetestet und bei der in den requirements aufgeführten version lande ich bei diesem fehler.
Es wäre nett, wenn Sie mir helfen könnten.
